BEGIN;

ALTER TABLE board_tasks           DROP CONSTRAINT IF EXISTS board_tasks_assignee_id_fkey;
ALTER TABLE board_tasks           DROP CONSTRAINT IF EXISTS board_tasks_created_by_fkey;
ALTER TABLE board_time_logs       DROP CONSTRAINT IF EXISTS board_time_logs_user_id_fkey;
ALTER TABLE board_task_activities DROP CONSTRAINT IF EXISTS board_task_activities_user_id_fkey;
ALTER TABLE notifications         DROP CONSTRAINT IF EXISTS notifications_user_id_fkey;
ALTER TABLE custom_events         DROP CONSTRAINT IF EXISTS custom_events_user_id_fkey;
ALTER TABLE reminders             DROP CONSTRAINT IF EXISTS reminders_user_id_fkey;
ALTER TABLE user_subscriptions    DROP CONSTRAINT IF EXISTS user_subscriptions_user_id_fkey;
ALTER TABLE task_completions      DROP CONSTRAINT IF EXISTS task_completions_user_id_fkey;
ALTER TABLE activity_logs         DROP CONSTRAINT IF EXISTS activity_logs_user_id_fkey;
ALTER TABLE chores                DROP CONSTRAINT IF EXISTS chores_added_by_fkey;
ALTER TABLE chores                DROP CONSTRAINT IF EXISTS chores_assigned_to_fkey;
ALTER TABLE chores                DROP CONSTRAINT IF EXISTS chores_completed_by_fkey;
ALTER TABLE password_reset_tokens DROP CONSTRAINT IF EXISTS password_reset_tokens_user_id_fkey;
ALTER TABLE refresh_tokens        DROP CONSTRAINT IF EXISTS refresh_tokens_user_id_fkey;
ALTER TABLE webauthn_credentials  DROP CONSTRAINT IF EXISTS webauthn_credentials_user_id_fkey;
ALTER TABLE invitations           DROP CONSTRAINT IF EXISTS invitations_invited_by_fkey;
ALTER TABLE notification_channels DROP CONSTRAINT IF EXISTS notification_channels_user_id_fkey;
ALTER TABLE habits                DROP CONSTRAINT IF EXISTS habits_user_id_fkey;
ALTER TABLE watchlist_items       DROP CONSTRAINT IF EXISTS watchlist_items_user_id_fkey;

ALTER TABLE users ADD COLUMN name TEXT NOT NULL DEFAULT '';
UPDATE users
SET name = trim(concat(coalesce(first_name, ''), ' ', coalesce(last_name, '')));
UPDATE users SET name = email WHERE name = '';
ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users ADD COLUMN _new_id TEXT;
UPDATE users SET _new_id = gen_random_uuid()::text;
ALTER TABLE users ALTER COLUMN _new_id SET NOT NULL;

ALTER TABLE board_tasks           ADD COLUMN _new_assignee_id TEXT;
ALTER TABLE board_tasks           ADD COLUMN _new_created_by  TEXT;
ALTER TABLE board_time_logs       ADD COLUMN _new_user_id     TEXT;
ALTER TABLE board_task_activities ADD COLUMN _new_user_id     TEXT;
ALTER TABLE notifications         ADD COLUMN _new_user_id     TEXT;
ALTER TABLE custom_events         ADD COLUMN _new_user_id     TEXT;
ALTER TABLE reminders             ADD COLUMN _new_user_id     TEXT;
ALTER TABLE user_subscriptions    ADD COLUMN _new_user_id     TEXT;
ALTER TABLE task_completions      ADD COLUMN _new_user_id     TEXT;
ALTER TABLE activity_logs         ADD COLUMN _new_user_id     TEXT;
ALTER TABLE chores                ADD COLUMN _new_added_by    TEXT;
ALTER TABLE chores                ADD COLUMN _new_assigned_to TEXT;
ALTER TABLE chores                ADD COLUMN _new_completed_by TEXT;
ALTER TABLE password_reset_tokens ADD COLUMN _new_user_id     TEXT;
ALTER TABLE refresh_tokens        ADD COLUMN _new_user_id     TEXT;
ALTER TABLE webauthn_credentials  ADD COLUMN _new_user_id     TEXT;
ALTER TABLE invitations           ADD COLUMN _new_invited_by  TEXT;
ALTER TABLE notification_channels ADD COLUMN _new_user_id     TEXT;
ALTER TABLE habits                ADD COLUMN _new_user_id     TEXT;
ALTER TABLE watchlist_items       ADD COLUMN _new_user_id     TEXT;

UPDATE board_tasks           t SET _new_assignee_id  = u._new_id FROM users u WHERE u.id = t.assignee_id;
UPDATE board_tasks           t SET _new_created_by   = u._new_id FROM users u WHERE u.id = t.created_by;
UPDATE board_time_logs       t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE board_task_activities t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE notifications         t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE custom_events         t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE reminders             t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE user_subscriptions    t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE task_completions      t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE activity_logs         t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id AND t.user_id IS NOT NULL;
UPDATE chores                t SET _new_added_by     = u._new_id FROM users u WHERE u.id = t.added_by;
UPDATE chores                t SET _new_assigned_to  = u._new_id FROM users u WHERE u.id = t.assigned_to AND t.assigned_to IS NOT NULL;
UPDATE chores                t SET _new_completed_by = u._new_id FROM users u WHERE u.id = t.completed_by AND t.completed_by IS NOT NULL;
UPDATE password_reset_tokens t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE refresh_tokens        t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE webauthn_credentials  t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE invitations           t SET _new_invited_by   = u._new_id FROM users u WHERE u.id = t.invited_by;
UPDATE notification_channels t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE habits                t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;
UPDATE watchlist_items       t SET _new_user_id      = u._new_id FROM users u WHERE u.id = t.user_id;

ALTER TABLE board_tasks           ALTER COLUMN _new_created_by   SET NOT NULL;
ALTER TABLE board_time_logs       ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE board_task_activities ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE notifications         ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE custom_events         ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE reminders             ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE user_subscriptions    ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE task_completions      ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE chores                ALTER COLUMN _new_added_by     SET NOT NULL;
ALTER TABLE password_reset_tokens ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE refresh_tokens        ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE webauthn_credentials  ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE invitations           ALTER COLUMN _new_invited_by   SET NOT NULL;
ALTER TABLE notification_channels ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE habits                ALTER COLUMN _new_user_id      SET NOT NULL;
ALTER TABLE watchlist_items       ALTER COLUMN _new_user_id      SET NOT NULL;

ALTER TABLE board_tasks           DROP COLUMN assignee_id;
ALTER TABLE board_tasks           DROP COLUMN created_by;
ALTER TABLE board_time_logs       DROP COLUMN user_id;
ALTER TABLE board_task_activities DROP COLUMN user_id;
ALTER TABLE notifications         DROP COLUMN user_id;
ALTER TABLE custom_events         DROP COLUMN user_id;
ALTER TABLE reminders             DROP COLUMN user_id;
ALTER TABLE user_subscriptions    DROP COLUMN user_id;
ALTER TABLE task_completions      DROP COLUMN user_id;
ALTER TABLE activity_logs         DROP COLUMN user_id;
ALTER TABLE chores                DROP COLUMN added_by;
ALTER TABLE chores                DROP COLUMN assigned_to;
ALTER TABLE chores                DROP COLUMN completed_by;
ALTER TABLE password_reset_tokens DROP COLUMN user_id;
ALTER TABLE refresh_tokens        DROP COLUMN user_id;
ALTER TABLE webauthn_credentials  DROP COLUMN user_id;
ALTER TABLE invitations           DROP COLUMN invited_by;
ALTER TABLE notification_channels DROP COLUMN user_id;
ALTER TABLE habits                DROP COLUMN user_id;
ALTER TABLE watchlist_items       DROP COLUMN user_id;

ALTER TABLE board_tasks           RENAME COLUMN _new_assignee_id  TO assignee_id;
ALTER TABLE board_tasks           RENAME COLUMN _new_created_by   TO created_by;
ALTER TABLE board_time_logs       RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE board_task_activities RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE notifications         RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE custom_events         RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE reminders             RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE user_subscriptions    RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE task_completions      RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE activity_logs         RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE chores                RENAME COLUMN _new_added_by     TO added_by;
ALTER TABLE chores                RENAME COLUMN _new_assigned_to  TO assigned_to;
ALTER TABLE chores                RENAME COLUMN _new_completed_by TO completed_by;
ALTER TABLE password_reset_tokens RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE refresh_tokens        RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE webauthn_credentials  RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE invitations           RENAME COLUMN _new_invited_by   TO invited_by;
ALTER TABLE notification_channels RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE habits                RENAME COLUMN _new_user_id      TO user_id;
ALTER TABLE watchlist_items       RENAME COLUMN _new_user_id      TO user_id;

ALTER TABLE users DROP CONSTRAINT users_pkey;
ALTER TABLE users DROP COLUMN id;
ALTER TABLE users RENAME COLUMN _new_id TO id;
ALTER TABLE users ADD PRIMARY KEY (id);

ALTER TABLE board_tasks ADD CONSTRAINT board_tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE board_tasks ADD CONSTRAINT board_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE board_time_logs ADD CONSTRAINT board_time_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE board_task_activities ADD CONSTRAINT board_task_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE custom_events ADD CONSTRAINT custom_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE reminders ADD CONSTRAINT reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE user_subscriptions ADD CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE task_completions ADD CONSTRAINT task_completions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE activity_logs ADD CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE chores ADD CONSTRAINT chores_added_by_fkey FOREIGN KEY (added_by) REFERENCES users(id);
ALTER TABLE chores ADD CONSTRAINT chores_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES users(id);
ALTER TABLE chores ADD CONSTRAINT chores_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES users(id);
ALTER TABLE password_reset_tokens ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE refresh_tokens ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE webauthn_credentials ADD CONSTRAINT webauthn_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE invitations ADD CONSTRAINT invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE notification_channels ADD CONSTRAINT notification_channels_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE habits ADD CONSTRAINT habits_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE watchlist_items ADD CONSTRAINT watchlist_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);

COMMIT;
