export const ADMIN_ENDPOINTS = {
  EXPORT: '/api/admin/export',
  IMPORT: '/api/admin/import',
  TRIGGER_ACTION: '/api/admin/trigger-action',
  SCHEDULED_JOBS: '/api/admin/scheduled-jobs',
  QUEUE_JOBS: (name: string) => `/api/admin/queues/${name}/jobs`,
  USERS: '/api/admin/users',
  DELETE_USER: (userId: number) => `/api/admin/users/${userId}`,
  INVITATIONS: '/api/admin/invitations',
  INVITE_USER: '/api/admin/invitations',
  RESEND_INVITATION: (id: number) => `/api/admin/invitations/${id}/resend`,
  REVOKE_INVITATION: (id: number) => `/api/admin/invitations/${id}`,
  TEST_EMAIL_TEMPLATES: '/api/admin/test-email-templates',
  TEST_EMAIL: '/api/admin/test-email',
  SESSIONS: '/api/admin/sessions',
  REVOKE_SESSION: (id: number) => `/api/admin/sessions/${id}`,
  REVOKE_USER_SESSIONS: (userId: number) => `/api/admin/sessions/user/${userId}`,
  PUSH_TOKENS: '/api/admin/push-tokens',
  DELETE_PUSH_TOKEN: (id: number) => `/api/admin/push-tokens/${id}`,
  WEB_PUSH: '/api/admin/web-push',
  DELETE_WEB_PUSH: (id: number) => `/api/admin/web-push/${id}`,
} as const;
