export const PLUGIN_ENDPOINTS = {
  BASE: '/api/plugins',
  JELLYFIN: '/api/plugins/jellyfin',
  RADARR: '/api/plugins/radarr',
  RADARR_PROFILES: '/api/plugins/radarr/profiles',
  SONARR: '/api/plugins/sonarr',
  SONARR_PROFILES: '/api/plugins/sonarr/profiles',
  QBITTORRENT: '/api/plugins/qbittorrent',
  SCRUTINY: '/api/plugins/scrutiny',
  NETDATA: '/api/plugins/netdata',
  WEATHER: '/api/plugins/weather',
  TMDB: '/api/plugins/tmdb',
  C411: '/api/plugins/c411',
  TORR9: '/api/plugins/torr9',
  LA_CALE: '/api/plugins/la-cale',
} as const;
