export const INTEGRATION_ENDPOINTS = {
  BASE: "/api/integrations",
  JELLYFIN: "/api/integrations/jellyfin",
  RADARR: "/api/integrations/radarr",
  RADARR_PROFILES: "/api/integrations/radarr/profiles",
  SONARR: "/api/integrations/sonarr",
  SONARR_PROFILES: "/api/integrations/sonarr/profiles",
  PROWLARR: "/api/integrations/prowlarr",
  JACKETT: "/api/integrations/jackett",
  QBITTORRENT: "/api/integrations/qbittorrent",
  SCRUTINY: "/api/integrations/scrutiny",
  BESZEL: "/api/integrations/beszel",
  ADGUARD: "/api/integrations/adguard",
  ADGUARD_PROTECTION: "/api/integrations/adguard/protection",
  WEATHER: "/api/integrations/weather",
  TMDB: "/api/integrations/tmdb",
  C411: "/api/integrations/c411",
  TORR9: "/api/integrations/torr9",
  LA_CALE: "/api/integrations/la-cale",
  HOME_ASSISTANT: "/api/integrations/home-assistant",
  HOME_ASSISTANT_ENTITIES: "/api/integrations/home-assistant/entities",
  UPTIMEKUMA: "/api/integrations/uptimekuma",
  UPTIMEKUMA_MONITORS: "/api/integrations/uptimekuma/monitors",
} as const;
