name: Build and Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build images
      run: |
        docker build -t hously-web:latest -f Dockerfile.web .
        docker build -t hously-api:latest -f Dockerfile.api .

    - name: Restart containers
      if: github.ref == 'refs/heads/main'
      run: |
        docker compose -f /home/samuelloranger/servers/hously/docker-compose.yml up -d --force-recreate hously-web hously-api
